### ISSUE TITLE
deobfuscate_string method

### ISSUE THREAD

**Issue by kaviyarasu74** [sladen/pat#1]
Dear sladen,

Appreciate your solution

Thanks for reading this actually am facing issue while compiling the python script gat.py in the line return ''.join([chr((ord(c) operation pnr.next()) & 0xff) for c in obfuscated]) its says invalid syntax near operation , chr is inbuild function having only one int parameter but here we have 3 int with no mathematical operation kindly guide me that what mathematical operators need to put or what params need to pass please.

Thanks

Kavi

**Comment by choddles** [comment]
I am sure i had this working with out altering the python source, I guess they altered something ?

**Comment by sladen** [comment]
Sorry, I missed this. @kaviyarasu74 @choddles could you supply an example test-case file, and the exact command being run.

_I don't have access to any of the machines myself, so I was only able to test/program against the example files one person emailed._

**Comment by sladen** [comment]
Another option could be Python 2 vs Python 3.  I think it was written for Python 2.  Either way, more examples of test files (and ideally a known-good cross-reference of what is in them), and some more work can be done on this.

**Comment by choddles** [comment]
I can supply specifically created test files as needed , i know the code worked fine previously.

**Comment by sladen** [comment]
Appears it was a change of allowable syntax in Python 2.7.2.  Kudos to @swardman for the fix.
